### ISSUE TITLE
switch TailwindCSS to ChakraUI

### ISSUE THREAD

**Issue by Tsugami** [MenheraBot/MenheraSite#15]
I added the wrong way because of lack of experience, sorry

**Comment by Tsugami** [comment]
@ySnoopyDogy what do you think we used chakra-ui instead of tailwindCSS?

**Comment by Daniel-Vinicius** [comment]
I can start migrating to chakra UI what do you think of a Pull request to start the migration?

**Comment by Tsugami** [comment]
> I can start migrating to chakra UI what do you think of a Pull request to start the migration?

Yes, but please do little prs, 1 add chakraUI and then convert page by page, one at a time and with responsive first

**Comment by NRotondaro** [comment]
I'm going to do it.

**Comment by ySnoopyDogy** [comment]
@NRotondaro heyy, i apreciate your help, but this issue is a mistake by our side. The entire website is going to change with a new design that we'll make with chakra. You dont need to work in this version. Thanks again for your help. In a brief, when the design is ready, you cam help us create the entire website from scratch, but now is not needed. Thanks again for your help

**Comment by Tsugami** [comment]
i don't mind switching to chakra UI now, so in the future we won't need to configure again

**Comment by ySnoopyDogy** [comment]
Go on then

**Comment by Tsugami** [comment]
we went back to tailwindcss
